image: oven/bun:latest

pipelines:
  default:
    - step:
        name: CI (install, lint, build)
        caches:
          - node            # caches your npm/yarn cache
        script:
          - bun install     # pull in next, react, etc.
          - bun run lint    # runs `next lint`
          - bun run build   # runs `next build`