export enum CUSTOMER_TYPE {
  INDIVIDUAL = 'INDIVIDUAL',
  BUSINESS = 'BUSINESS',
}

export enum CUSTOMER_STATUS {
  ACTIVE = 'ACTIVE',
  ARCHIVED = 'ARCHIVED',
}

export enum PAYMENT_TYPE {
  PREPAID = 'PREPAID',
  CREDIT = 'CREDIT',
}

export enum PAYMENT_TERM_TYPE {
  OFTHEFOLLOWINGMONTH = 'OFFOLLOWINGMONTH',
  OFCURRENTMONTH = 'OFCURRENTMONTH',
  DAYSAFTERBILLMONTH = 'DAYSAFTERBILLMONTH',
  DAYSAFTERBILLDATE = 'DAYSAFTERBILLDATE'
}