import { DOCKET_STATUS, DOCKET_TYPE } from './docket-enums';
import { Job } from './job';
import { Address } from './address';

export interface Docket {
  id: number;
  job: Job;
  docketType?: DOCKET_TYPE;
  docketNumber: string;
  status: DOCKET_STATUS;
  jobLineItemId: number;
  productName: string;
  productId: number;
  quarrySupplierId: number;
  quarrySupplierName: string;
  productUoM: string;
  productSell: number;
  loadSize: number;
  truckType?: string;
  truckSellUom?: string;
  truckSell?: number;
  truckSellQty?: number;
  totalProductSell: number;
  totalTruckSell?: number;
  sutotal: number;
  gst: number;
  totalInvoice: number;
  deliveryDate: string;
  poNumber?: string;
  pickUpAddress?: Address;
  deliveryAddress?: Address;
  startTimeWindow: string;
  endTimeWindow: string;
  contactName: string;
  contactPhone: string;
  docketEmail: string;
  notes?: string;
  createdBy: string;
  lastModifiedBy: string;
  createdAt: string;
  updatedAt: string;
  version: number;
  isDeleted: boolean;
}
