export enum DOCKET_STATUS {
  UNASSIGNED = 'UNASSIGNED',
  ASSIGNED = 'ASSIGNED',
  IN_TRANSIT = 'IN_TRANSIT',
  STOPPED = 'STOPPED',
  ARRIVED = 'ARRIVED',
  DELIVERED = 'DELIVERED',
  INVOICED = 'INVOICED',
  VOIDED = 'VOIDED',
  PENDING = 'PENDING',
  PREPARING = 'PREPARING',
  READY = 'READY',
  COLLECTED = 'COLLECTED',
  CASH_SALE = 'CASH_SALE',
}

export enum DOCKET_TYPE {
  DELIVERY = 'DELIVERY',
  COLLECTION = 'COLLECTION',
}
