import { DOCKET_STATUS, DOCKET_TYPE } from './docket-enums';
import { Job } from './job';
import { Address } from './address';
import { DriverDTO } from './driver';
import { CustomerDTO } from './customer';

export interface Docket {
  id: number;
  job: Job;
  docketType?: DOCKET_TYPE;
  docketNumber: string;
  status: DOCKET_STATUS;
  jobLineItemId: number;
  productName: string;
  productId: number;
  quarrySupplierId: number;
  quarrySupplierName: string;
  productUoM: string;
  productSell: number;
  loadSize: number;
  truckType?: string;
  truckSellUom?: string;
  truckSell?: number;
  truckSellQty?: number;
  totalProductSell: number;
  totalTruckSell?: number;
  sutotal: number;
  gst: number;
  totalInvoice: number;
  deliveryDate: string;
  poNumber?: string;
  pickUpAddress?: Partial<Address>;
  deliveryAddress?: Partial<Address>;
  startTimeWindow: string;
  endTimeWindow: string;
  contactName: string;
  contactPhone: string;
  docketEmail: string;
  notes?: string;
  createdBy: string;
  lastModifiedBy: string;
  createdAt: string;
  updatedAt: string;
  version: number;
  isDeleted: boolean;
}

export interface DocketDTO {
  id: number;
  docketNumber: string;
  jobId: number;
  truckInspectionRequired: boolean;

  // Remove this once API is ready
  preStartRequired?: boolean;

  jobItemId: number;
  docketStatus: DOCKET_STATUS;
  stopReason?: string;
  resumeReason?: string;
  cancelledReason?: string;
  voidedReason?: string;
  stoppedAt?: string;
  resumedAt?: string;
  pickUpAddressId: number;
  pickUpAddress: Partial<Address>;
  deliveryAddressId: number;
  deliveryAddress: Partial<Address>;
  deliveryCollectionDate: Date;
  deliveryCollectionStartTime: string;
  deliveryCollectionEndTime: string;
  customerContactName: string;
  customerContactPhone: string;
  docketEmailRecipients: string[];
  notes: string;
  driverId: number;
  driver?: DriverDTO;
  truckId: number;
  driverChecklistId: number;
  truckChecklistId: number;
  truckType: string;
  loadSize: number;
  deliveredLoadSize: number;
  deliveryDistanceQuantity: number;
  deliveryDistanceUom: string;
  grossTruckWeight: number;
  tareTruckWeight: number;
  actualMaterialWeight: number;
  deliveredAt: string;
  signatureImage: string;
  deliveryNotes: string;
  deliveryPhotos: string[];
  gpsLocation: string;
  productEstimatedVolume: number;
  purchaseOrder: string;
  totalInvoice: number;
  job: {
    id: number;
    jobNumber: string;
    customerId: number;
    customerName?: string;
    customerDto?: CustomerDTO;
    accountManagerName?: string;
    projectName: string;
    jobStatus: JOB_STATUS;
    poNumber: string;
    contactPersonName: string;
    contactPersonPhone: string;
    docketEmail: string;
    uninvoicedDockets: number;
    quoteId: number;
    additionalEmails: string[];
    estimatedStartDate: string;
    startTimeWindow: string;
    endTimeWindow: string;
    version: number;
  };
  jobItem: {
    id: number;
    jobId: number;
    jobItemType: JOB_LINE_ITEM_TYPE;
    customerDeliveryAddressId: number;
    customerDeliveryAddress: CustomerDeliveryAddress;
    productId: number;
    product: {
      id: number;
      productName: string;
      productCode: string;
      materialId: number;
      densityTonnagePerM3: number;
      productDescription: string;
      isActive: boolean;
      version: number;
    };
    quarrySupplierId: number;
    quarrySupplierName?: string;
    quarrySupplier?: Partial<QuarrySupplier>;
    totalQuantityRequired: number;
    allocatedQuantity: number;
    remainingQuantity: number;
    productCostUom: string;
    productCostQty: number;
    productCostPrice: number;
    totalProductCostPrice: number;
    productSellUom: string;
    productSellQty: number;
    productSellPrice: number;
    totalProductSellPrice: number;
    truckCostUom: string;
    truckCostQty: number;
    truckCostPrice: number;
    totalTruckCostPrice: number;
    truckSellUom: string;
    truckSellQty: number;
    truckSellPrice: number;
    totalTruckSellPrice: number;
    truckType: string;
    grossProfit: number;
    version: number;
  };
  pickUpAddress: {
    id: number;
    googlePlaceId: string;
    formattedAddress: string;
    streetDetailsPrimary: string;
    streetDetailsOptional: string;
    city: string;
    suburb: string;
    state: string;
    postcode: string;
    country: string;
    latitude: number;
    longitude: number;
    version: number;
  };
  deliveryAddress: {
    id: number;
    googlePlaceId: string;
    formattedAddress: string;
    streetDetailsPrimary: string;
    streetDetailsOptional: string;
    city: string;
    suburb: string;
    state: string;
    postcode: string;
    country: string;
    latitude: number;
    longitude: number;
    version: number;
  };
  driverChecklist: {
    id: number;
    checklistDate: string;
    completedAt: string;
    checklistStatus: string;
    hasIssues: boolean;
    notes: string;
    version: number;
  };
  truckChecklist: {
    id: number;
    checklistDate: string;
    completedAt: string;
    checklistStatus: string;
    hasIssues: boolean;
    notes: string;
    version: number;
  };
  version: number;
  isDeleted: boolean;
  createdBy: string;
  createdAt: string;
  updatedAt: string;
  lastModifiedBy: string;
}
