import { DOCKET_STATUS, DOCKET_TYPE } from './docket-enums';
import { Job } from './job';
import { CustomerDeliveryAddress } from './address';

export interface DocketDTO {
  id: number;
  docketNumber: string;
  jobId: number;
  jobItemId: number;
  docketStatus: DOCKET_STATUS;
  stopReason?: string;
  stoppedAt?: string;
  resumedAt?: string;
  pickUpAddressId?: number;
  purchaseOrder?: string;
  deliveryCollectionDate?: string;
  deliveryCollectionStartTime?: string;
  deliveryCollectionEndTime?: string;
  customerContactName?: string;
  customerContactPhone?: string;
  docketEmailRecipients?: string[];
  notes?: string;
  driverId?: number;
  truckId?: number;
  truckType?: string;
  loadSize?: number;
  grossTruckWeight?: number;
  tareTruckWeight?: number;
  deliveryDistanceQuantity?: number;
  deliveryDistanceUom?: string;
  productEstimatedVolume?: number;
  deliveryStartedAt?: string;
  arrivedAt?: string;
  deliveredAt?: string;
  arrivalLatitude?: number;
  arrivalLongitude?: number;
  deliveryLatitude?: number;
  deliveryLongitude?: number;
  signatureImage?: string;
  deliveryNotes?: string;
  unloadedPhotos?: string[];
  receivedPhotos?: string[];
  version: number;
  createdBy?: string;
  createdAt?: string;
  updatedAt?: string;
  lastModifiedBy?: string;
}

export interface Docket {
  id: number;
  job: Job;
  docketType?: DOCKET_TYPE;
  docketNumber: string;
  status: DOCKET_STATUS;
  jobLineItemId: number;
  productName: string;
  productId: number;
  quarrySupplierId: number;
  quarrySupplierName: string;
  productUoM: string;
  productSell: number;
  loadSize: number;
  truckType?: string;
  truckSellUom?: string;
  truckSell?: number;
  truckSellQty?: number;
  totalProductSell: number;
  totalTruckSell?: number;
  sutotal: number;
  gst: number;
  totalInvoice: number;
  deliveryDate: string;
  poNumber?: string;
  pickUpAddress?: Partial<CustomerDeliveryAddress>;
  deliveryAddress?: Partial<CustomerDeliveryAddress>;
  startTimeWindow: string;
  endTimeWindow: string;
  contactName: string;
  contactPhone: string;
  docketEmail: string;
  notes?: string;
  createdBy: string;
  lastModifiedBy: string;
  createdAt: string;
  updatedAt: string;
  version: number;
  isDeleted: boolean;
}
