export enum DRIVER_STATUS {
  ACTIVE = 'ACTIVE',
  DEACTIVATED = 'DEACTIVATED',
  ON_DUTY = 'ON_DUTY',
  PENDING_INVITATION = 'PENDING_INVITATION',
}

export enum DRIVER_TYPE {
  INTERNAL = 'INTERNAL',
  SUBCONTRACTOR = 'SUBCONTRACTOR',
}
