export enum RECOVERY_MODE {
  RECOVER = 'RECOVER',
  ABSORB = 'ABSORB',
}

export enum EFFECTIVE_SOURCE {
  GLOBAL_DEFAULT = 'GLOBAL_DEFAULT',
  CUSTOMER_OVERRIDE = 'CUSTOMER_OVERRIDE',
  FROZEN_DOCKET = 'FROZEN_DOCKET',
}
