export enum JOB_STATUS {
  IN_PROGRESS = 'IN_PROGRESS',
  PAUSED = 'PAUSED',
  SETTLED = 'SETTLED',
  ACTIVE = 'ACTIVE',
  CANCELLED = 'CANCELLED',
  COMPLETED = 'COMPLETED',
}

export enum JOB_LINE_ITEM_TYPE {
  COLLECTION = 'COLLECTION',
  DELIVERY = 'DELIVERY',
}
