export enum TRUCK_STATUS {
  ACTIVE = 'ACTIVE',
  ON_DUTY = 'ON_DUTY',
  DEACTIVATED = 'DEACTIVATED',
}

export enum TRUCK_TYPE {
  TRUCK = 'TRUCK',
  TRUCK_AND_TRAILER = 'TRUCK_AND_TRAILER',
  SEMI_TRAILER = 'SEMI_TRAILER',
  RIGID_TRUCK = 'RIGID_TRUCK',
  FLATBED = 'FLATBED',
  TIPPER = 'TIPPER',
  TANDEM = 'TANDEM',
  QUAD = 'QUAD',
  TRI_AXLE = 'TRI_AXLE',
  TAUTLINER = 'TAUTLINER',
  CRANE_TRUCK = 'CRANE_TRUCK',
}
