export enum TRUCK_STATUS {
  AVAILABLE = 'AVAILABLE',
  ACTIVE = 'ACTIVE',
  ON_DUTY = 'ON_DUTY',
  DEACTIVATED = 'DEACTIVATED',
}

export enum TRUCK_TYPE {
  TRUCK = 'TRUCK',
  TIPPER = 'TIPPER',
  SEMI_TRAILER = 'SEMI TRAILER',
  GENERIC = 'GENERIC',
}

export enum TRUCK_BODY_TYPE {
  ALUMINIUM = 'ALUMINIUM',
  STEEL = 'STEEL',
}
